apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ingress-backendconfig
spec:
  healthCheck:
    requestPath: /healthz
    port: 8080
  # securityPolicy:
  #   name: "ingress-security-policy"
  timeoutSec: 40
  logging:
    enable: true
    sampleRate: 0.5  